project:
  type: website

website:
  title: "Vidhi A. Sharma"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Projects"
        href: projects.qmd
  page-footer:
    center: "© 2025 Vidhi A. Sharma"

format:
  html:
    theme:
      light: flatly
    css: styles.css
    toc: true
