project:
  type: website
  output-dir: _site

website:
  title: "Vidhi A. Sharma"
  navbar:
    background: "#444444"  # Dark grey background
    foreground: "#ffffff"  # White text for navigation items
    left:
      - href: index.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: experience.qmd
        text: Experience
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: default
    css: styles.css
    toc: true
