project:
  type: website

website:
  title: "Vidhi A. Sharma"
  navbar:
    left:
      - text: About
        href: about.qmd
      - text: Projects
        href: projects.qmd
      - text: CV
        href: cv.qmd
      - text: Contact
        href: contact.qmd

    format:
  html:
    theme: default
    css: styles.css


output-dir: docs


